# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Account\Application\:
        resource: '../src/Account/Application/**/*Handler.php'

    App\Account\Domain\:
        resource: '../src/Account/Domain/*'
        exclude:
            - '../src/Account/Domain/Model/*'

    App\Account\Infra\:
        resource: '../src/Account/Infra/*'

    App\UserInterface\Web\Symfony\:
        resource: '../src/UserInterface/Web/Symfony/*'
